services:
  melvin:
    image: ghcr.io/lordluceus/melvin:master
    depends_on:
      - db
    restart: unless-stopped
    container_name: melvin
    env_file:
      - .env

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: melvin_db
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
