services:
  melvin:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: on-failure
    container_name: melvin
    env_file:
      - .env

  db:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
